controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_cats:
  path: "/cats"
  controller: 'App\Controller\CatController::index'

# config/routes.yaml
add_favorite_cat:
  path: "/add-favorite-cat/{catId}"
  controller: 'App\Controller\UserLikeCatController::addFavoriteCat'
